### ISSUE TITLE
kiosk mode no longer working after last update in HACS today

### ISSUE THREAD

**Issue by hassuser** [maykar/kiosk-mode#65] opened 2021-06-24 22:41 UTC
this are my settings
kiosk_mode:
  hide_header: true
  ignore_mobile_settings: true

in others just have this.
kiosk_mode:
  kiosk: true

And this are the logs
Logger: frontend.js.latest.202106030
Source: components/system_log/__init__.py:190
First occurred: 12:25:47 AM (7 occurrences)
Last logged: 12:28:42 AM

http://xxx.xxx.x.x:8123/hacsfiles/kiosk-mode/kiosk-mode.js?hacstag=303101606166:49:122 ReferenceError: regeneratorRuntime is not defined
http://xxx.xxx.x.x:8123/hacsfiles/kiosk-mode/kiosk-mode.js?hacstag=303101606166:49:144 ReferenceError: Can't find variable: regeneratorRuntime

Running all Apple devices of all ages, the all stopped hiding headers and sidebars. Before it was just the older ones having problems

**Comment by sweetgman** [comment] 2021-06-25 00:19
same with me but i get the following

Logger: frontend.js.latest.202106030
Source: components/system_log/__init__.py:190
First occurred: 8:16:28 PM (2 occurrences)
Last logged: 8:16:29 PM

http://xxx.xxx.xxx.xxx:8123/hacsfiles/kiosk-mode/kiosk-mode.js?hacstag=303101606166:49:126 Uncaught ReferenceError: regeneratorRuntime is not defined
http://xxx.xxx.xxx.xxx:8123/lovelace-mobile/bedroom3?kiosk:0:0 Uncaught

**Comment by lunaw** [comment] 2021-06-25 02:19
mi too

**Comment by lunaw** [comment] 2021-06-25 02:19
me too

**Comment by myxu13** [comment] 2021-06-25 03:43
Me too, can anyone solve this problem?

**Comment by w1tw0lf** [comment] 2021-06-25 07:50
sitting with the same issue here as well.

**Comment by dsegantx** [comment] 2021-06-25 13:58
Confirm 1.6.6 breaks my envt.  Both android/fire tablets and iPad show headers with 1.6.6.  Rollback to 1.6.5 restores.

Please fix.

**Comment by maykar** [comment] 2021-06-25 14:15
Give the latest release a try and be sure to clear the cache of all devices if you're still having issues before reporting back.

**Comment by maykar** [comment] 2021-06-25 14:17
Closing as duplicate of #63

**Closed by maykar** 2021-06-25 14:17 UTC
Labels: duplicate
