### ISSUE TITLE
Hide help button in kiosk mode

### ISSUE THREAD

**Issue by allanbell3d** [maykar/kiosk-mode#53] opened 2021-01-28 19:33 UTC
Hi there! First of all would like to thank you for your work. This component is great, I was using custom header to do the same thing and I was really bummed when it was archived, I´m really happy you made an alternative.  

I just have one request: Would it be possible to hide the help button from the header?

I use kiosk mode to hide the side bar and only display the header with several tabs and having the help button taking up screen space is a real nuisance. 

Really hope this is possible! Thanks a lot!

**Comment by maykar** [comment] 2021-01-28 20:13
This is a duplicate of another issue #38, read my responses there for why I won't be adding this to kiosk-mode and a way to do this with card-mod. I will add that another reason I won't be adding this is because it fits better in another project I am planning, but that's all I'm going to say about it at the moment.

**Closed by maykar** 2021-01-28 20:13 UTC
