### ISSUE TITLE
version 1.6.6 breaks on Google hub displays

### ISSUE THREAD

**Issue by scooper1** [maykar/kiosk-mode#66] opened 2021-06-25 11:44 UTC
version 1.6.5  works no problem on the latest home assistant build
1.6.6. does not appear to working at all   side bar and top bar fully visible

**Comment by maykar** [comment] 2021-06-25 14:16
Give the latest release a try and be sure to clear the cache of all devices if you're still having issues before reporting back.

Closing as duplicate of #63

**Closed by maykar** 2021-06-25 14:16 UTC
Labels: duplicate
