### ISSUE TITLE
Toggle kiosk mode from picture-elements

### ISSUE THREAD

**Issue by tbarbette** [maykar/kiosk-mode#40] opened 2020-12-24 10:27 UTC
Hi all,

I have a picture element showing my floor plan, and I'd like a button to toggle kiosk mode. The following rewrite the URL but it does nothing:

```
  - type: icon
    icon: 'mdi:home'
    tap_action:
      action: navigate
      navigation_path: /lovelace/plan?kiosk
    style:
      right: 10%
      bottom: 10%
```

Any idea? And then it does not even support "toggling". It's for a raspberry pi touchscreen without keyboard, so when I go to kiosk mode I'm kind of locked on the floor plan.

**Comment by KTibow** [comment] 2020-12-24 14:53
Use `browser_mod.window_reload`. And as for toggling, just reload again without the `?kiosk`.

**Comment by tbarbette** [comment] 2020-12-26 10:51
I tried what was proposed on #35 and it did not work either:
```
- platform: template
  switches:
    kiosk_mode:
      turn_on:
        - service: browser_mod.navigate
          data:
            navigation_path: /lovelace/homekit?kiosk
        - service: browser_mod.window_reload  
      turn_off:
        - service: browser_mod.navigate
          data:
            navigation_path: /lovelace/homekit?disable_km
        - service: browser_mod.window_reload
```
It does nothing when I click. I use Chrome on windows.

**Comment by KTibow** [comment] 2020-12-26 17:23
Not even change the URL?

**Comment by KTibow** [comment] 2020-12-26 17:24
That's because configuration.yaml switches don't know which device to execute those commands on.

**Comment by tbarbette** [comment] 2020-12-27 07:58
Ha yes, it worked yesterday out of the blue.  What would you recommend?

Funny enough, browser_mod's README goes in great lengths to explain what is the deviceId, even how to change it, but does not say how to find the ID of the current device...

**Comment by KTibow** [comment] 2020-12-27 14:31
Open the browser console (press f12, go to the console tab) and it should show it.

**Comment by tbarbette** [comment] 2020-12-27 14:38
Ah yes, thanks!  :) 

I'm okay for now, still I'll keep this open as a feature request, as it needs a second mod, and is still not super clean as I'd like to toggle the kiosk mode on the current window (the behavior is still heratic with multiple tabs).

Also it would be great to add the console trick in the README.

**Comment by KTibow** [comment] 2020-12-27 20:07
> Also it would be great to add the console trick in the README.

You mean in browser_mod? Just click on the readme.md file in the file view, hit the edit icon, add your changes, and you can send a PR.

**Comment by maykar** [comment] 2020-12-31 16:00
Duplicate of #35

When I get the chance I will add a feature to enable/disable kiosk mode on an entities state, like a input boolean, etc.

**Closed by maykar** 2020-12-31 16:00 UTC
