### ISSUE TITLE
Uncaught TypeError: Cannot read property 'config' of undefined

### ISSUE THREAD

**Issue by ijustlikeit** [maykar/kiosk-mode#37] opened 2020-12-09 20:11 UTC
Getting this error:
2020-12-09 12:56:29 ERROR (MainThread) [frontend.js.latest.202011112] https://xxx.duckdns.org/hacsfiles/kiosk-mode/kiosk-mode.js:18:15 Uncaught TypeError: Cannot read property 'config' of undefined.

Kiosk Mode 1.4.7
Info:
**System Health

Home Assistant Core Integration

version: 0.118.5
installation_type: Home Assistant OS
dev: false
hassio: true
docker: true
virtualenv: false
python_version: 3.8.6
os_name: Linux
os_version: 4.19.127-v7l
arch: armv7l
timezone: America/xxx

Home Assistant Cloud

logged_in: false
can_reach_cert_server: ok
can_reach_cloud_auth: ok
can_reach_cloud: ok

Hass.io

host_os: HassOS 4.17
update_channel: stable
supervisor_version: 2020.12.6
docker_version: 19.03.12
disk_total: 28.7 GB
disk_used: 17.7 GB
healthy: true
supported: true
board: rpi4
supervisor_api: ok
version_api: ok
installed_addons: File editor (5.2.0), Samba share (9.3.0), Duck DNS (1.12.4), NGINX Home Assistant SSL proxy (3.0.1), Let's Encrypt (4.11.0), SSH & Web Terminal (7.8.0), Log Viewer (0.9.1)

Lovelace

dashboards: 3
mode: yaml
views: 14
resources: 12**

edit:  At first thought it (this error) hung my screen; but it didn't was another issue unrelated.  

This error randomly will appear and upon refresh of panel does not other problems.

**Comment by kloggy** [comment] 2020-12-10 17:51
Me too.
And have been getting this since this add-on was first released but have had no time to investigate. It doesn't cause me a serious problem as my screens don't hang.

However I don't get a kiosk mode on my tablet which uses a separate dashboard.

```
title: Hall Panel

kiosk_mode:
  kiosk: true

views:
  - !include lovelace/hall_panel/view_hall_panel_home.yaml
```

Sorry this is brief. I have no time with HA at the moment for personal reasons but will happily help troubleshoot this if more info is needed.

**Comment by maykar** [comment] 2020-12-31 15:58
Duplicate of #36

**Closed by maykar** 2020-12-31 15:58 UTC
