### ISSUE TITLE
hide only menu button

### ISSUE THREAD

**Issue by fdepalo** [maykar/kiosk-mode#58] opened 2021-02-23 17:44 UTC
It is possible to add a hide_menu_button option to block ui modification?

Thank you

**Comment by maykar** [comment] 2021-02-23 18:00
Duplicate of #53 and #38

Read those issues for my reasoning behind not including this in kiosk-mode and towards the end of #38 it's explained how to do this with card mod.

**Closed** 2021-02-23 18:01 UTC
Labels: duplicate
