### ISSUE TITLE
Kiosk mode not working after v1.6.5

### ISSUE THREAD

**Issue by henriklund** [maykar/kiosk-mode#68] opened 2021-06-30 18:15 UTC
From v1.6.6 and onwards Kiosk mode no longer hides sidebar or header.

Visited from Chrom (incognito):
- Console shows 'version 1.6.7'
- the only warning I see is
`kiosk-mode.js?hacstag=303101606167:20 Lovelace config not found, continuing with default configuration.`
- Config
```
kiosk_mode:
  admin_settings:
    ignore_entity_settings: true
  non_admin_settings:
    hide_sidebar: true
    hide_header: true
    hide_overflow: true

```
- Devices affected are Windows (Chrome) and iPads (2x) iOS 14

Interestingly enough 1.6.5 shows following error:

```
kiosk-mode.js?hacstag=303101606165:37 Uncaught (in promise) ReferenceError: regeneratorRuntime is not defined
    at v (kiosk-mode.js?hacstag=303101606165:37)
    at k (kiosk-mode.js?hacstag=303101606165:37)
    at kiosk-mode.js?hacstag=303101606165:44
v @ kiosk-mode.js?hacstag=303101606165:37
k @ kiosk-mode.js?hacstag=303101606165:37
(anonymous) @ kiosk-mode.js?hacstag=303101606165:44
Promise.then (async)
(anonymous) @ kiosk-mode.js?hacstag=303101606165:43
```

**Comment by lue42** [comment] 2021-06-30 18:21
Same as above:

Edge Version 91.0.864.59 on Windows 10, logged into HA as a "user"

Console shows 1.7.0
No warnings, Kiosk-Mode shows 1.7.0

```
kiosk_mode:
  non_admin_settings:
    hide_header: true
    hide_sidebar: true
```

It is not working on IOS 12.5.4 on iPhone 5s - I fully reset cache in Safari on phone.

**Comment by henriklund** [comment] 2021-06-30 18:22
Unfortunately v.1.6.5 is no longer to be found in HACS so I am stuck with a non functioning 1.6.6 :/

**Comment by maykar** [comment] 2021-06-30 18:26
Fortunately, all the releases exist on github: https://github.com/maykar/kiosk-mode/releases/tag/1.6.5

**Comment by maykar** [comment] 2021-06-30 18:28
Closing as duplicate of #68

**Closed by maykar** 2021-06-30 18:28 UTC

**Comment by henriklund** [comment] 2021-06-30 18:55
Probably me being stupid but dropping kiosk-mode.,js in place does not change anything. Only option seems to be a manual install -> too much of a hassle.

**Comment by maykar** [comment] 2021-06-30 18:58
Sorry, you'd also need to delete HACS's compressed file `kiosk-mode.js.gz`, but I'm about to release another fix

**Comment by maykar** [comment] 2021-06-30 19:03
Please give 1.7.1 a try and if you're still having issues post to the open issue

**Comment by lue42** [comment] 2021-06-30 19:31
Sorry, no - It is still not working on IOS 12.5.4 on iPhone 5s - I fully reset cache in Safari on phone.
It doesn't show right away, but after a number of seconds it shows.  Also, as reported in the other thread the screen does periodic refreshes, which seems to make the sidebar show after the first reset

**Comment by maykar** [comment] 2021-06-30 19:38
This would be an unrelated issue. As I mentioned in the other thread, please create a new issue with the requested information: https://github.com/maykar/kiosk-mode/issues/63#issuecomment-871619543

**Comment by lue42** [comment] 2021-06-30 19:40
> This would be an unrelated issue. As I mentioned in the other thread, please create a new issue with the requested information: [#63 (comment)](https://github.com/maykar/kiosk-mode/issues/63#issuecomment-871619543)

I am not commenting (as an issue) for the refreshing, only that it is a possible related symptom.

The sidebar is still appearing for me on IOS 12.5.4 on iPhone 5s.  1.7.1 has not resolved that.

**Comment by maykar** [comment] 2021-06-30 19:45
The issues that others were having, including the author of this issue, have been resolved. I am asking if you would create a new issue, with a title describing your issue and provide the information requested in the comment linked above. 

Issues with a title like this one and the larger one before it end up causing confusion as everyone with an issue after 1.6.5 will post there even though their issues are unrelated. For example: There were 4 separate issues that were in the  `"kiosk mode no longer working after 2021.6 HA update"` thread.

**Comment by milkplus27** [comment] 2021-06-30 21:08
i'm experiencing the same issues as @lue42 - constantly refreshing dashboard that makes the header/sidebar reappear.

this is after updating to the latest HA Core and v1.7.1 of kiosk-mode

**Comment by stephenmetts** [comment] 2021-06-30 21:15
I am as well.

**Comment by maykar** [comment] 2021-06-30 22:12
Please read my comments above, create a new issue and provide there info I've requested

**Comment by maykar** [comment] 2021-06-30 22:22
I've made post for this issue, please provide any info you can there: https://github.com/maykar/kiosk-mode/issues/69
